# the following workflow will run whenever a pull request closes. The if_merged job will only run if the pull request was also merged.
name: Run your pull_request workflow when PR req merges
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
